### ISSUE TITLE
Develop a system for zero-config project management

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/roadmap#9]
- [x] Publish a [vision](https://blog.jaraco.com/vision-for-scalable-OSS-development/)
- [x] Develop a [prototype builder](/coherent-oss/coherent.build)
- [ ] Identify a way to share (GitHub) workflows
- [ ] Develop a way to derive more metadata from the source tree
- [ ] Prove the builder across several projects
- [ ] Identify challenges or blockers
- [ ] Develop a framework for building docs

**Comment by jaraco** [comment]
One challenge I've identified is installing from GitHub source. If a project doesn't have a pyproject.toml, pip has no idea about how to build it:

```
 @ pip-run git+https://github.com/jaraco/tempora@experiment/coherent
ERROR: git+https://github.com/jaraco/tempora@experiment/coherent does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Traceback (most recent call last):
  File "/opt/homebrew/bin/pip-run", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pip_run/__init__.py", line 13, in run
    with deps.load(*deps.not_installed(pip_args)) as home:
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pip_run/deps.py", line 100, in load
    subprocess.check_call(cmd, env=env)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/opt/homebrew/opt/python@3.12/bin/python3.12', '-m', 'pip', 'install', '-t', PosixPath('/var/folders/f2/2plv6q2n7l932m2x004jlw340000gn/T/pip-run-hky8fqrm'), 'git+https://github.com/jaraco/tempora@experiment/coherent')' returned non-zero exit status 1.
```

We could require each project to have the minimal [pyproject.toml](https://github.com/coherent-oss/coherent.build/blob/8805d25b96c4e76fbea6d548813060a847bd1a2f/pyproject.toml), but that becomes a shared artifact that needs to be managed across projects. Is there another way that a tool like pip or uv could infer those settings? Or get them from environment variables?

**Comment by jaraco** [comment]
Another issue these projects will face - how to manage development environment defaults, such as setting the recommended defaults for ruff?

Perhaps the system should follow the same principle as skeleton did for `.gitignore` - that is, it should be defined somewhere at a system level or environment level.

Or maybe there should be a parent repo that contains the relevant projects and that repo should contain the ruff defaults. Something like:

`py` --> `coherent` --> `build`

Where `py` is `coherent-oss/python` and would contain the settings for all Python projects such as ruff best practices (and could contain projects outside coherent-oss). `coherent` is `coherent-oss/coherent` (?) and would contain settings or concerns specific to projects using the `coherent` namespace. And  `build` is `coherent-oss/coherent.build`.

**Comment by jaraco** [comment]
Ugh. It appears as if ruff only allows for discovering settings from [one file](https://docs.astral.sh/ruff/configuration/#config-file-discovery). That file can explicitly include other files, but there's no support for composition (like git's global/user/local hierarchy). I think what this means is that anything that runs linting (including an editor that's autosaving, a pre-commit hook, a check at test time, or a manually-invoked formatting/lint operation) will have to be aware of the common config in order to honor it.

**Comment by jaraco** [comment]
Another challenge I've encountered pertains to running tests, namely doctests. The problem with running doctests in a shallow repo is that relative references are no longer viable. Consider in `coherent.build` (0.4.0):

```python
# __init__.py

from . import discovery
```

Although the `discovery` module exists alongside `__init__.py` and both will be/are found in `coherent/build` after installation, pytest "discovers" `__init__.py` as a plain module and not in the context of `coherent.build`, so fails thus:

```
__________________________________________________________ ERROR collecting __init__.py __________________________________________________________
ImportError while importing test module '/Users/jaraco/code/coherent-oss/coherent.build/__init__.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
__init__.py:32: in <module>
    from . import discovery
E   ImportError: attempted relative import with no known parent package
```
